apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: world-ruby
    app.kubernetes.io/instance: world-ruby-xyzz
    app.kubernetes.io/version: "0.9.1"
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: helloworld
    app.kubernetes.io/managed-by: helm
  name: world-ruby
  namespace: supreme-doodle
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: world-ruby
      app.kubernetes.io/instance: world-ruby-xyzz
      app.kubernetes.io/version: "0.9.1"
      app.kubernetes.io/component: service
      app.kubernetes.io/part-of: helloworld
      app.kubernetes.io/managed-by: helm
  template:
    metadata:
      labels:
        app.kubernetes.io/name: world-ruby
        app.kubernetes.io/instance: world-ruby-xyzz
        app.kubernetes.io/version: "0.9.1"
        app.kubernetes.io/component: service
        app.kubernetes.io/part-of: helloworld
        app.kubernetes.io/managed-by: helm
    spec:
      containers:
      - name: world-ruby
        image: ghcr.io/scrogatl/doodle-world-ruby:latest
        imagePullPolicy: Always
        env:
        - name: SHARD
          value: "blue"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: NEW_RELIC_LICENSE_KEY
          value:  "{{ .Values.nr_key }}"
        ports:
        - containerPort: 5003
          name: application
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: world-ruby
  namespace: supreme-doodle
  labels:
    app.kubernetes.io/name: world-ruby
    app.kubernetes.io/instance: world-ruby-xyzz
    app.kubernetes.io/version: "0.9.1"
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: helloworld
    app.kubernetes.io/managed-by: helm

spec: 
  selector:
    app.kubernetes.io/name: world-ruby
    app.kubernetes.io/instance: world-ruby-xyzz
    app.kubernetes.io/version: "0.9.1"
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: helloworld
    app.kubernetes.io/managed-by: helm
  type: ClusterIP
  ports:
  - name: http
    # protocol: TCP
    appProtocol: http
    port: 5003